title: "Math2001's blog"
baseURL: https://math2001.github.io
languageCode: en-us
metaDataFormat: yaml
preserveTaxonomyNames: true
publishBranch: master

theme: fasty
author:
  math2001: Mathieu Paturel
copyright: © Mathieu Paturel 2017
enableEmoji: true

blackfriday:
  hrefTargetBlank: true

params:
  disableSearch: true # not available yet
  description: ":thinking: Just an other blog I guess. :smiley:"
  github_username: math2001
  themefolderpath: themes/fasty
  avatar:
    vector: img/math2001.svg
    raster: img/math2001.png
    alt: Math2001's logo
  favicon: img/math2001.png
  social:
    github: math2001
    twitter: _math2001
    stackoverflow: math2001
    dev.to: math2001


menu:
  main:
    - url: /post/
      name: Posts
      weight: 1
      pre: "Sections"
    - url: /project/
      name: Projects
      weight: 5
    - url: /categories/
      name: Categories
      weight: 15
      pre: "Classifications"
    - url: /tags/
      name: Tags
      weight: 20

  home:
    - url: /post/
      name: Posts
      weight: 1
    - url: /project/
      name: Projects
      weight: 5

