title: "Math2001's blog"
baseURL: https://math2001.github.io
languageCode: en-us
metaDataFormat: yaml
preserveTaxonomyNames: true

theme: fasty
author:
  math2001: "Mathieu Paturel"
description: My blog
copyright: '© Mathieu Paturel 2017'

params:
  description: My personal blog
  github_username: math2001

menu:
  main:
    - url: /post/
      name: Posts
      weight: 1
    - url: /project/
      name: Projects
      weight: 2

#     icon:
#       - url: mailto:australie.p@gmail.com
#         name: envelope-o
#         weight: 1
#       - url: https://github.com/math2001
#         name: github
#         weight: 2
#       - url: https://twitter.com/_math2001
#         name: twitter
#         weight: 3
