title: "Math2001's blog"
baseURL: https://math2001.github.io
languageCode: en-us
metaDataFormat: yaml
preserveTaxonomyNames: true
publishDir: docs
publishBranch: gh-pages

theme: fasty
author:
  math2001: "Mathieu Paturel"
description: My blog
copyright: '© Mathieu Paturel 2017'
enableEmoji: true
hrefTargetBlank: true
newContentEditor: "vim"

params:
  dev: true
  disableSearch: true # not available yet
  description: My personal blog
  github_username: math2001
  themefolderpath: "themes/fasty"
  avatar:
    path: img/math2001.svg
    alt: Math2001's logo
  favicon: img/math2001.png

menu:
  main:
    - url: /post/
      name: Posts
      weight: 1
    - url: /project/
      name: Projects
      weight: 5
    - url: /tip/
      name: Tips
      weight: 10
    - url: /categories/
      pre: "|"
      name: Categories
      weight: 15
    - url: /tags/
      name: Tags
      weight: 20

  home:
    - url: /post/
      name: Posts
      weight: 1
    - url: /project/
      name: Projects
      weight: 5
    - url: /tip/
      name: Tips
      weight: 10

#     icon:
#       - url: mailto:australie.p@gmail.com
#         name: envelope-o
#         weight: 1
#       - url: https://github.com/math2001
#         name: github
#         weight: 2
#       - url: https://twitter.com/_math2001
#         name: twitter
#         weight: 3
